/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface GasOptimizerDemoInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activeScoreTotal"
      | "addUsers"
      | "batchBumpScore"
      | "findUsersByPrefix"
      | "mode"
      | "owner"
      | "paused"
      | "setNicknames"
      | "setPaused"
      | "totalScore"
      | "userList"
      | "users"
      | "version"
      | "whitelist"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "NicknameUpdated" | "ScoreBumped" | "UserAdded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "activeScoreTotal",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addUsers",
    values: [AddressLike[], BigNumberish[], string]
  ): string;
  encodeFunctionData(
    functionFragment: "batchBumpScore",
    values: [AddressLike[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "findUsersByPrefix",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "mode", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setNicknames",
    values: [AddressLike[], string[]]
  ): string;
  encodeFunctionData(functionFragment: "setPaused", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "totalScore",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "userList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "users", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "whitelist",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "activeScoreTotal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addUsers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchBumpScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "findUsersByPrefix",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mode", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setNicknames",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPaused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "totalScore", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userList", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "users", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "whitelist", data: BytesLike): Result;
}

export namespace NicknameUpdatedEvent {
  export type InputTuple = [account: AddressLike, nickname: string];
  export type OutputTuple = [account: string, nickname: string];
  export interface OutputObject {
    account: string;
    nickname: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScoreBumpedEvent {
  export type InputTuple = [account: AddressLike, newScore: BigNumberish];
  export type OutputTuple = [account: string, newScore: bigint];
  export interface OutputObject {
    account: string;
    newScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserAddedEvent {
  export type InputTuple = [account: AddressLike, score: BigNumberish];
  export type OutputTuple = [account: string, score: bigint];
  export interface OutputObject {
    account: string;
    score: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GasOptimizerDemo extends BaseContract {
  connect(runner?: ContractRunner | null): GasOptimizerDemo;
  waitForDeployment(): Promise<this>;

  interface: GasOptimizerDemoInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activeScoreTotal: TypedContractMethod<[], [bigint], "view">;

  addUsers: TypedContractMethod<
    [accounts: AddressLike[], scores: BigNumberish[], prefix: string],
    [void],
    "nonpayable"
  >;

  batchBumpScore: TypedContractMethod<
    [accounts: AddressLike[], amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  findUsersByPrefix: TypedContractMethod<[prefix: string], [string[]], "view">;

  mode: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  paused: TypedContractMethod<[], [boolean], "view">;

  setNicknames: TypedContractMethod<
    [accounts: AddressLike[], names: string[]],
    [void],
    "nonpayable"
  >;

  setPaused: TypedContractMethod<[nextPaused: boolean], [void], "nonpayable">;

  totalScore: TypedContractMethod<[], [bigint], "view">;

  userList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  users: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, boolean, string] & {
        score: bigint;
        joinedAt: bigint;
        active: boolean;
        nickname: string;
      }
    ],
    "view"
  >;

  version: TypedContractMethod<[], [bigint], "view">;

  whitelist: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activeScoreTotal"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addUsers"
  ): TypedContractMethod<
    [accounts: AddressLike[], scores: BigNumberish[], prefix: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchBumpScore"
  ): TypedContractMethod<
    [accounts: AddressLike[], amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "findUsersByPrefix"
  ): TypedContractMethod<[prefix: string], [string[]], "view">;
  getFunction(
    nameOrSignature: "mode"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "setNicknames"
  ): TypedContractMethod<
    [accounts: AddressLike[], names: string[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPaused"
  ): TypedContractMethod<[nextPaused: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalScore"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "userList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "users"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, boolean, string] & {
        score: bigint;
        joinedAt: bigint;
        active: boolean;
        nickname: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "whitelist"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getEvent(
    key: "NicknameUpdated"
  ): TypedContractEvent<
    NicknameUpdatedEvent.InputTuple,
    NicknameUpdatedEvent.OutputTuple,
    NicknameUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ScoreBumped"
  ): TypedContractEvent<
    ScoreBumpedEvent.InputTuple,
    ScoreBumpedEvent.OutputTuple,
    ScoreBumpedEvent.OutputObject
  >;
  getEvent(
    key: "UserAdded"
  ): TypedContractEvent<
    UserAddedEvent.InputTuple,
    UserAddedEvent.OutputTuple,
    UserAddedEvent.OutputObject
  >;

  filters: {
    "NicknameUpdated(address,string)": TypedContractEvent<
      NicknameUpdatedEvent.InputTuple,
      NicknameUpdatedEvent.OutputTuple,
      NicknameUpdatedEvent.OutputObject
    >;
    NicknameUpdated: TypedContractEvent<
      NicknameUpdatedEvent.InputTuple,
      NicknameUpdatedEvent.OutputTuple,
      NicknameUpdatedEvent.OutputObject
    >;

    "ScoreBumped(address,uint256)": TypedContractEvent<
      ScoreBumpedEvent.InputTuple,
      ScoreBumpedEvent.OutputTuple,
      ScoreBumpedEvent.OutputObject
    >;
    ScoreBumped: TypedContractEvent<
      ScoreBumpedEvent.InputTuple,
      ScoreBumpedEvent.OutputTuple,
      ScoreBumpedEvent.OutputObject
    >;

    "UserAdded(address,uint256)": TypedContractEvent<
      UserAddedEvent.InputTuple,
      UserAddedEvent.OutputTuple,
      UserAddedEvent.OutputObject
    >;
    UserAdded: TypedContractEvent<
      UserAddedEvent.InputTuple,
      UserAddedEvent.OutputTuple,
      UserAddedEvent.OutputObject
    >;
  };
}
