/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TempContract } from "./TempContract";
export * as factories from "./factories";
export { TempContract__factory } from "./factories/TempContract__factory";
