/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GasOptimizerDemo } from "./GasOptimizerDemo";
export * as factories from "./factories";
export { GasOptimizerDemo__factory } from "./factories/GasOptimizerDemo__factory";
